version: "3.2"
services:
  backend:
    image: 1science/sbt
    environment:
      - TEST=true
    volumes:
      - .:/app
      - ~/.ivy2:/root/.ivy2
    command: sbt run

  kafka:
    image: spotify/kafka
    ports:
        - "2181:2181"
        - "9092:9092"